targets:
  $default:
    builders:
      graphql_codegen:
        options:
          schema: lib/graphql/service/schema.graphqls
          queries_glob: lib/graphql/service/**/*.graphql
          output: lib/graphql/generated/graphql_api.graphql.dart

