query PokemonDetail($id: Int!, $langId: Int!) {
    pokemon_v2_pokemon_by_pk(id: $id) {
        id
        name
        height
        weight
        pokemon_v2_pokemontypes {
            pokemon_v2_type {
                name
            }
        }
        pokemon_v2_pokemonstats {
            base_stat
            pokemon_v2_stat {
                name
            }
        }
        pokemon_v2_pokemonabilities {
            is_hidden
            pokemon_v2_ability {
                name
                pokemon_v2_abilitynames(where: {language_id: {_eq: $langId}}) {
                    name
                }
                pokemon_v2_abilityflavortexts(where: {language_id: {_eq: $langId}}, limit: 1, order_by: {version_group_id: desc}) {
                    flavor_text
                }
                pokemon_v2_abilityeffecttexts(where: {language_id: {_eq: $langId}}) {
                    short_effect
                }
            }
        }
        pokemon_v2_pokemonspecy {
            id
            name
            gender_rate
            is_legendary
            is_mythical
            generation_id
            pokemon_v2_generation {
                pokemon_v2_region {
                    name
                }
            }
            pokemon_v2_pokemonegggroups {
                pokemon_v2_egggroup {
                    name
                }
            }
            pokemon_v2_pokemonspeciesflavortexts(where: {language_id: {_eq: $langId}}, limit: 1) {
                flavor_text
            }
            pokemon_v2_evolutionchain {
                pokemon_v2_pokemonspecies {
                    id
                    name
                    evolves_from_species_id
                    pokemon_v2_pokemonevolutions {
                        min_level
                        min_happiness
                        min_beauty
                        min_affection
                        needs_overworld_rain
                        turn_upside_down
                        time_of_day
                        gender_id
                        relative_physical_stats
                        pokemon_v2_evolutiontrigger { name }
                        pokemon_v2_item { name }
                        pokemon_v2_move { name }
                        pokemon_v2_location { name }
                        pokemon_v2_type { name }
                    }
                    pokemon_v2_pokemons(limit: 1, where: {is_default: {_eq: true}}) {
                        id
                        name
                        pokemon_v2_pokemonforms(limit: 1) {
                            form_name
                            is_mega
                            pokemon_v2_pokemonformtypes {
                                pokemon_v2_type { name }
                            }
                        }
                    }
                }
            }
            pokemon_v2_pokemons {
                id
                name
                pokemon_v2_pokemonforms {
                    form_name
                    is_mega
                    pokemon_v2_pokemonformtypes {
                        pokemon_v2_type { name }
                    }
                }
            }
        }
        pokemon_v2_pokemonmoves {
            level
            move_id
            pokemon_v2_movelearnmethod {
                name
            }
            version_group_id
            pokemon_v2_move {
                name
                pokemon_v2_movenames(where: {language_id: {_eq: $langId}}) {
                    name
                }
                power
                accuracy
                pp
                pokemon_v2_type {
                    name
                }
                pokemon_v2_movedamageclass {
                    name
                }
                pokemon_v2_moveflavortexts(where: {language_id: {_eq: $langId}}, limit: 1) {
                    flavor_text
                }
            }
        }
        pokemon_v2_encounters(distinct_on: location_area_id) {
            pokemon_v2_locationarea {
                pokemon_v2_location {
                    name
                    pokemon_v2_locationnames(where: {language_id: {_eq: $langId}}) {
                        name
                    }
                    pokemon_v2_region {
                        name
                        pokemon_v2_regionnames(where: {language_id: {_eq: $langId}}) {
                            name
                        }
                    }
                }
            }
            pokemon_v2_version {
                name
                pokemon_v2_versionnames(where: {language_id: {_eq: $langId}}) {
                    name
                }
            }
        }
    }
}